FROM bitnami/postgresql:15
COPY init.sql /docker-entrypoint-initdb.d/
VOLUME ["/bitnami/postgresql"]
EXPOSE 5432
ENTRYPOINT ["/opt/bitnami/scripts/postgresql/entrypoint.sh"]
CMD ["/opt/bitnami/scripts/postgresql/run.sh"]
